/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ieeeP1451Project.h"

/* NOTE: customized code of `ncap-demo' project STARTS here */

#include	<stdlib.h>
#include	<stdio.h>
#include	<time.h>

#define		CHAR_ARRAY_SIZE 20

/* Used for transmmiting sensor data in textual strings. */
/* By `fake' here we mean the system is not connected to any real sensor. */
/* The readout is just some random value. */
char	fake_sensor_data[CHAR_ARRAY_SIZE];
/* base (average) value */
float	fake_sensor_data_temperature_base	= 24.0;
float	fake_sensor_data_pressure_base		= 101.0;
/* specifies how to format the string to be transmiitted */
char	fake_sensor_data_temperature_format[]	= "%2.2f";
char	fake_sensor_data_pressure_format[]	= "%3.2f";
/* specifies the length of the string to be transmiitted */
int	fake_sensor_data_length_temperature	= 5;
int	fake_sensor_data_length_pressure	= 6;
/* Some virtual actuators for clients to control. */
/* Since no real actuators exist either, we call them `fake' ones. */
int	fake_switch_status_relay		= 0;
int	fake_switch_status_led			= 0;

/* returns a float value ranging from 0. to 1. */
float	randf() {
	return ((float) rand()) / ((float) RAND_MAX);
}

/* NOTE: customized code of `ncap-demo' project ENDS here */

/** Initializes the ieeeP1451Project module */
void
init_ieeeP1451Project(void)
{
    const oid seTemperature_oid[] = { 1,3,6,1,4,1,7934,1451,1,1 };
    const oid sePressure_oid[] = { 1,3,6,1,4,1,7934,1451,1,2 };
    const oid acRelay_oid[] = { 1,3,6,1,4,1,7934,1451,2,1 };
    const oid acLed_oid[] = { 1,3,6,1,4,1,7934,1451,2,2 };

  DEBUGMSGTL(("ieeeP1451Project", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("seTemperature", handle_seTemperature,
                               seTemperature_oid, OID_LENGTH(seTemperature_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sePressure", handle_sePressure,
                               sePressure_oid, OID_LENGTH(sePressure_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("acRelay", handle_acRelay,
                               acRelay_oid, OID_LENGTH(acRelay_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("acLed", handle_acLed,
                               acLed_oid, OID_LENGTH(acLed_oid),
                               HANDLER_CAN_RWRITE
        ));

	/* NOTE: customized code of `ncap-demo' project STARTS here */

	/* random number seed init */
	srand(time(0));

	/* NOTE: customized code of `ncap-demo' project ENDS here */
}

int
handle_seTemperature(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    /* NOTE: customized code of `ncap-demo' project STARTS here */

    float fake_sensor_data_value;

    /* NOTE: customized code of `ncap-demo' project ENDS here */

    switch(reqinfo->mode) {

        case MODE_GET:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

		/* add some fake noise */
		fake_sensor_data_value = fake_sensor_data_temperature_base + (randf()-0.5)*2.0;
		/* formmat the result into a `xx.xx'-like look and store it in a char array */
		snprintf(fake_sensor_data, CHAR_ARRAY_SIZE, 
		         fake_sensor_data_temperature_format, fake_sensor_data_value);
		/* put the fake sensor value into the response message */
            snmp_set_var_typed_value(requests->requestvb, /* the var-binding part in the message */
	                             ASN_OCTET_STR, /* type */
                                     fake_sensor_data, /* pointer to the data */
                                     fake_sensor_data_length_temperature /* length of data*/ );

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_seTemperature\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_sePressure(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    /* NOTE: customized code of `ncap-demo' project STARTS here */

    float fake_sensor_data_value;

    /* NOTE: customized code of `ncap-demo' project ENDS here */

    switch(reqinfo->mode) {

        case MODE_GET:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

		fake_sensor_data_value = fake_sensor_data_pressure_base + (randf()-0.5)*2.0;
		snprintf(fake_sensor_data, CHAR_ARRAY_SIZE, 
		         fake_sensor_data_pressure_format, fake_sensor_data_value);
            snmp_set_var_typed_value(requests->requestvb,
	                             ASN_OCTET_STR,
                                     fake_sensor_data,
                                     fake_sensor_data_length_pressure);

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sePressure\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_acRelay(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

            snmp_set_var_typed_value(requests->requestvb,
	                             ASN_INTEGER,
                                     &fake_switch_status_relay,
                                     4 /* size of `int' type */ );

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        // case MODE_SET_RESERVE1:
        //         /* or you could use netsnmp_check_vb_type_and_size instead */
        //     ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        //     if ( ret != SNMP_ERR_NOERROR ) {
        //         netsnmp_set_request_error(reqinfo, requests, ret );
        //     }
        //     break;

        // case MODE_SET_RESERVE2:
        //     /* XXX malloc "undo" storage buffer */
        //     if (/* XXX if malloc, or whatever, failed: */) {
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        //     }
        //     break;

        // case MODE_SET_FREE:
        //     /* XXX: free resources allocated in RESERVE1 and/or
        //        RESERVE2.  Something failed somewhere, and the states
        //        below won't be called. */
        //     break;

        case MODE_SET_ACTION:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

		/* Treat the bytes in the data part of the request message as */
		/* `int' type and assign the target variable with the `int' variable's value */
		fake_switch_status_relay = *((int *) requests->requestvb->buf);

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;

        // case MODE_SET_COMMIT:
        //     /* XXX: delete temporary storage */
        //     if (/* XXX: error? */) {
        //         /* try _really_really_ hard to never get to this point */
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
        //     }
        //     break;

        // case MODE_SET_UNDO:
        //     /* XXX: UNDO and return to previous value for the object */
        //     if (/* XXX: error? */) {
        //         /* try _really_really_ hard to never get to this point */
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
        //     }
        //     break;

        // default:
        //     /* we should never get here, so this is a really bad error */
        //     snmp_log(LOG_ERR, "unknown mode (%d) in handle_acRelay\n", reqinfo->mode );
        //     return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_acLed(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

            snmp_set_var_typed_value(requests->requestvb, 
                                     ASN_INTEGER,
                                     &fake_switch_status_led,
                                     4);

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        // case MODE_SET_RESERVE1:
        //         /* or you could use netsnmp_check_vb_type_and_size instead */
        //     ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
        //     if ( ret != SNMP_ERR_NOERROR ) {
        //         netsnmp_set_request_error(reqinfo, requests, ret );
        //     }
        //     break;

        // case MODE_SET_RESERVE2:
        //     /* XXX malloc "undo" storage buffer */
        //     if (/* XXX if malloc, or whatever, failed: */) {
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
        //     }
        //     break;

        // case MODE_SET_FREE:
        //     /* XXX: free resources allocated in RESERVE1 and/or
        //        RESERVE2.  Something failed somewhere, and the states
        //        below won't be called. */
        //     break;

        case MODE_SET_ACTION:
		/* NOTE: customized code of `ncap-demo' project STARTS here */

		fake_switch_status_led = *((int *) requests->requestvb->buf);

		/* NOTE: customized code of `ncap-demo' project ENDS here */
            break;

        // case MODE_SET_COMMIT:
        //     /* XXX: delete temporary storage */
        //     if (/* XXX: error? */) {
        //         /* try _really_really_ hard to never get to this point */
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
        //     }
        //     break;

        // case MODE_SET_UNDO:
        //     /* XXX: UNDO and return to previous value for the object */
        //     if (/* XXX: error? */) {
        //         /* try _really_really_ hard to never get to this point */
        //         netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
        //     }
        //     break;

        // default:
        //     /* we should never get here, so this is a really bad error */
        //     snmp_log(LOG_ERR, "unknown mode (%d) in handle_acLed\n", reqinfo->mode );
        //     return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
