/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEEP1451PROJECT_H
#define IEEEP1451PROJECT_H

/* function declarations */
void init_ieeeP1451Project(void);
Netsnmp_Node_Handler handle_seTemperature;
Netsnmp_Node_Handler handle_sePressure;
Netsnmp_Node_Handler handle_acRelay;
Netsnmp_Node_Handler handle_acLed;
Netsnmp_Node_Handler handle_acLcd;

#endif /* IEEEP1451PROJECT_H */
